// ============================================================================
// POST-MEETING CRM SYNC (HubSpot as system of record).
//
// After a meeting, for an ALLOWLISTED company (Luminare only this phase):
//  - AUTO (no approval): log the meeting summary + a direct "Watch recording"
//    link onto the deal/company. Notes/meeting linkage is additive and safe.
//  - SUGGEST (approval): a Slack message proposing the deal STAGE move + any
//    standard field changes, with an "Apply CRM updates" button. Replies can
//    edit it; the button applies through the gated server path (the agent never
//    writes to HubSpot directly).
//
// The suggestion is generated by the shared agent (oneshot, read-only HubSpot),
// which returns stage/field changes in human terms; the SERVER resolves the
// stage label → internal id and performs the gated writes.
// ============================================================================

import { kv } from "@/lib/kv-client";
import { postToChannel, salesChannel } from "@/lib/slack";
import { selfBaseUrl, boardLink } from "@/lib/work-items";
import { isCompanyWritable } from "@/lib/hubspot-guard";
import {
  logMeetingToHubSpot,
  updateDealStage,
  updateDealProperties,
  getDealPipelines,
  getCompanyContacts,
  hubspotDealUrl,
} from "@/lib/hubspot";

export const CRM_APPLY_ACTION_ID = "pm_crm_apply";
const CRM_TTL = 7 * 24 * 3600;

function recordingUrl(botId: string): string {
  const base = process.env.PUBLIC_BASE_URL ?? "https://gtm-jet.vercel.app";
  return `${base}/board/meeting/${botId}`;
}

export type CrmFieldSuggestion = {
  object: "deal" | "company";
  property: string;
  currentValue: string | null;
  suggestedValue: string;
  reason: string;
};

export type CrmProposal = {
  botId: string;
  companyId: string;
  companyName: string;
  dealId: string;
  dealName: string;
  pipeline: string;
  stages: string[];
  currentStageLabel: string | null;
  suggestedStageId: string | null;
  suggestedStageLabel: string | null;
  stageReason: string | null;
  fieldSuggestions: CrmFieldSuggestion[];
};

export function crmProposalKey(botId: string): string {
  return `postmeeting:crm:bot:${botId}`;
}

export async function getStoredCrmProposal(botId: string): Promise<CrmProposal | null> {
  if (!botId) return null;
  return (await kv.get<CrmProposal>(crmProposalKey(botId)).catch(() => null)) ?? null;
}

// ----------------------------------------------------------------------------
// Suggestion generation (agent oneshot, read-only HubSpot)
// ----------------------------------------------------------------------------

function buildCrmPrompt(botId: string): string {
  return [
    `You are preparing a CRM-update SUGGESTION after a meeting. HubSpot is the system of record. READ-ONLY: do NOT write to HubSpot — only search/read.`,
    `MEETING BOT ID: ${botId}`,
    `STEP 1 — read the transcript + meta from the cloned KB ('_unsorted' is a real slug, so glob): corpora/success/customers/*/meetings/${botId}/transcript.txt and meta.json.`,
    `STEP 2 — identify the COMPANY the meeting is about and look it up in HubSpot (search companies). Get its id + name. Find the primary OPEN deal: its id, name, current dealstage LABEL, pipeline, and the pipeline's stage labels IN ORDER.`,
    `STEP 3 — write a concise meeting summary as HTML for hs_meeting_body: one short <p> recap + a "<p><strong>Next steps</strong></p>" followed by a <ul> of next steps with owners. Keep it tight.`,
    `STEP 4 — recommend whether the deal STAGE should change given what happened, and to which stage (MUST be one of the pipeline's stage labels, verbatim). One-line reason. If no change is warranted, suggestedStageLabel=null.`,
    `STEP 5 — suggest any STANDARD HubSpot deal/company field updates the conversation supports (e.g. closedate, amount, dealname). Only standard properties. Empty array if none.`,
    `Return ONLY a single fenced \`\`\`json block, nothing after it:`,
    "```json",
    `{`,
    `  "companyId": string, "companyName": string, "dealId": string, "dealName": string,`,
    `  "pipeline": string, "currentStageLabel": string, "stages": [string],`,
    `  "meetingSummaryHtml": string,`,
    `  "suggestedStageLabel": string|null, "stageReason": string|null,`,
    `  "fieldSuggestions": [ { "object": "deal"|"company", "property": string, "currentValue": string|null, "suggestedValue": string, "reason": string } ]`,
    `}`,
    "```",
    `CRITICAL: your FINAL message must be ONLY the single fenced json block.`,
  ].join("\n");
}

type RawCrm = {
  companyId?: string; companyName?: string; dealId?: string; dealName?: string;
  pipeline?: string; currentStageLabel?: string; stages?: string[];
  meetingSummaryHtml?: string;
  suggestedStageLabel?: string | null; stageReason?: string | null;
  fieldSuggestions?: CrmFieldSuggestion[];
};

function parseCrm(answer: string): RawCrm | null {
  const blocks: string[] = [];
  const fenced = answer.match(/```(?:json)?\s*([\s\S]*?)```/gi);
  if (fenced) for (const b of fenced) blocks.push(b.replace(/```(?:json)?\s*/i, "").replace(/```$/, "").trim());
  blocks.push(answer);
  for (const b of blocks) {
    const start = b.indexOf("{");
    const end = b.lastIndexOf("}");
    if (start < 0 || end <= start) continue;
    try {
      const o = JSON.parse(b.slice(start, end + 1)) as RawCrm;
      if (o && o.companyId && o.dealId) return o;
    } catch { /* try next */ }
  }
  return null;
}

async function runOneshot(question: string, userEmail: string, reqId: string): Promise<string | null> {
  const secret = process.env.MCP_INTERNAL_SECRET;
  if (!secret) return null;
  try {
    const res = await fetch(`${selfBaseUrl()}/api/agent/oneshot`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-reddy-internal": secret },
      body: JSON.stringify({ question, userEmail, oneshotRequestId: reqId, pollTimeoutMs: 600_000 }),
    });
    const json = (await res.json().catch(() => null)) as { ok?: boolean; answer?: string } | null;
    if (json?.ok && json.answer) return json.answer;
  } catch { /* swallow */ }
  return null;
}

// Resolve a stage LABEL → internal id by searching ALL deal pipelines.
// getDealPipelines() is keyed by internal pipeline id (not label); the agent
// emits labels — so we scan every pipeline's stages for the label.
async function resolveStageIdByLabel(label: string | null): Promise<string | null> {
  if (!label) return null;
  const pipelines = await getDealPipelines().catch(() => null);
  if (!pipelines) return null;
  for (const stages of pipelines.values()) {
    const hit = stages.find((s) => s.label === label);
    if (hit) return hit.id;
  }
  return null;
}

export type CrmProposeResult = {
  ok: boolean;
  skipped?: string;
  companyName?: string;
  loggedMeetingId?: string | null;
  suggestedStageLabel?: string | null;
  fieldCount?: number;
  slackTs?: string;
  error?: string;
};

// Orchestrator: generate → auto-log meeting+recording → post Slack suggestion.
export async function proposeCrmFromMeeting(botId: string, opts?: { force?: boolean }): Promise<CrmProposeResult> {
  // Post-once per botId: the recall webhook re-fires on every reconcile once a
  // transcript exists, so without this claim each retry re-runs the oneshot and
  // posts a duplicate CRM card. Released only on transient failure so it can retry.
  const claimKey = `postmeeting:crm:claim:${botId}`;
  let claimedHere = false;
  const releaseClaim = async () => { if (claimedHere) await kv.del(claimKey).catch(() => {}); };
  try {
    if (!botId) return { ok: false, error: "missing botId" };
    if (!opts?.force) {
      const claimed = await kv.set(claimKey, new Date().toISOString(), { nx: true, ex: CRM_TTL }).catch(() => "errored");
      if (claimed === null) return { ok: true, skipped: "already-posted" };
      if (claimed !== "errored") claimedHere = true;
    }
    const runnerEmail = process.env.POST_MEETING_AGENT_EMAIL || "adam@reddy.io";
    const answer = await runOneshot(buildCrmPrompt(botId), runnerEmail, `crm:${botId}`);
    if (!answer) { await releaseClaim(); return { ok: false, error: "crm agent unavailable or empty" }; }
    const raw = parseCrm(answer);
    if (!raw || !raw.companyId || !raw.dealId) { await releaseClaim(); return { ok: false, error: "could not parse crm JSON" }; }

    // GATE: only allowlisted companies get any write (auto-log included).
    if (!isCompanyWritable(raw.companyId)) {
      return { ok: true, skipped: `company ${raw.companyId} not writable (allowlist)`, companyName: raw.companyName };
    }

    // Resolve the suggested stage label → internal id (searches all pipelines;
    // getDealPipelines is keyed by internal pipeline id, and the agent reports
    // human labels, so we match by label across pipelines).
    const suggestedStageId = await resolveStageIdByLabel(raw.suggestedStageLabel ?? null);

    // AUTO-LOG (no approval): meeting summary + direct recording link.
    const recUrl = recordingUrl(botId);
    const bodyHtml =
      (raw.meetingSummaryHtml ?? `<p>Meeting on ${raw.companyName ?? "the account"}.</p>`) +
      `<p>▶ <a href="${recUrl}">Watch the recording &amp; read the transcript</a></p>`;
    const contacts = await getCompanyContacts(raw.companyId).catch(() => []);
    const contactIds = contacts.slice(0, 10).map((c) => c.id);
    // Idempotent: log the meeting at most once per botId so re-runs (replays,
    // a retried webhook) don't create duplicate HubSpot meeting engagements.
    const logKey = `crm:meeting:${botId}`;
    let loggedMeetingId = await kv.get<string>(logKey).catch(() => null);
    if (!loggedMeetingId) {
      try {
        loggedMeetingId = await logMeetingToHubSpot({
          companyId: raw.companyId,
          dealId: raw.dealId,
          contactIds,
          title: `${raw.companyName ?? "Meeting"} — meeting`,
          bodyHtml,
          startISO: new Date().toISOString(),
        });
        if (loggedMeetingId) await kv.set(logKey, loggedMeetingId, { ex: 90 * 24 * 3600 }).catch(() => {});
      } catch { /* surfaced below as no meeting id */ }
    }

    // Stash the SUGGESTION (stage + fields) for the Apply button / chat-edit.
    const proposal: CrmProposal = {
      botId,
      companyId: raw.companyId,
      companyName: raw.companyName ?? "the account",
      dealId: raw.dealId,
      dealName: raw.dealName ?? "the deal",
      pipeline: raw.pipeline ?? "",
      stages: Array.isArray(raw.stages) ? raw.stages : [],
      currentStageLabel: raw.currentStageLabel ?? null,
      suggestedStageId,
      suggestedStageLabel: raw.suggestedStageLabel ?? null,
      stageReason: raw.stageReason ?? null,
      fieldSuggestions: Array.isArray(raw.fieldSuggestions) ? raw.fieldSuggestions : [],
    };
    await kv.set(crmProposalKey(botId), proposal, { ex: CRM_TTL }).catch(() => {});

    // Post the Slack suggestion.
    const dealUrl = await hubspotDealUrl(raw.dealId).catch(() => null);
    let slackTs: string | undefined;
    const channel = salesChannel();
    if (channel) {
      const res = await postToChannel(channel, buildCrmMessage(proposal, recUrl, dealUrl, !!loggedMeetingId)).catch(() => ({ ts: undefined }));
      slackTs = res.ts;
      if (slackTs) await kv.set(`postmeeting:crm:ts:${slackTs}`, proposal, { ex: CRM_TTL }).catch(() => {});
    }

    return {
      ok: true,
      companyName: proposal.companyName,
      loggedMeetingId,
      suggestedStageLabel: proposal.suggestedStageLabel,
      fieldCount: proposal.fieldSuggestions.length,
      ...(slackTs ? { slackTs } : {}),
    };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

// ----------------------------------------------------------------------------
// Apply (gated) — invoked by the Slack "Apply CRM updates" button.
// ----------------------------------------------------------------------------

export type CrmApplyResult = { ok: boolean; stageMoved: boolean; fieldsUpdated: number; errors: string[] };

export async function executeCrmProposal(proposal: CrmProposal): Promise<CrmApplyResult> {
  const res: CrmApplyResult = { ok: true, stageMoved: false, fieldsUpdated: 0, errors: [] };

  if (proposal.suggestedStageId) {
    try {
      res.stageMoved = await updateDealStage(proposal.companyId, proposal.dealId, proposal.suggestedStageId);
    } catch (err) {
      res.errors.push(`stage: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // Standard DEAL field updates only (company-field writes deferred with #3).
  const dealProps: Record<string, string> = {};
  for (const f of proposal.fieldSuggestions) {
    if (f.object === "deal" && f.property && f.suggestedValue) dealProps[f.property] = f.suggestedValue;
  }
  if (Object.keys(dealProps).length > 0) {
    try {
      const ok = await updateDealProperties(proposal.companyId, proposal.dealId, dealProps);
      if (ok) res.fieldsUpdated = Object.keys(dealProps).length;
      else res.errors.push("field update failed");
    } catch (err) {
      res.errors.push(`fields: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  res.ok = res.errors.length === 0;
  return res;
}

// ----------------------------------------------------------------------------
// Slack message
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Chat-to-edit — a reply in the CRM-suggestion thread edits the SUGGESTION
// (stage/fields) via a oneshot; re-stashes + re-posts with the Apply button.
// The bot never writes HubSpot here — only the gated Apply button does.
// ----------------------------------------------------------------------------

type RawCrmEdit = {
  suggestedStageLabel?: string | null;
  stageReason?: string | null;
  fieldSuggestions?: CrmFieldSuggestion[];
};

function parseCrmEdit(answer: string): RawCrmEdit | null {
  const blocks: string[] = [];
  const fenced = answer.match(/```(?:json)?\s*([\s\S]*?)```/gi);
  if (fenced) for (const b of fenced) blocks.push(b.replace(/```(?:json)?\s*/i, "").replace(/```$/, "").trim());
  blocks.push(answer);
  for (const b of blocks) {
    const start = b.indexOf("{");
    const end = b.lastIndexOf("}");
    if (start < 0 || end <= start) continue;
    try {
      return JSON.parse(b.slice(start, end + 1)) as RawCrmEdit;
    } catch { /* next */ }
  }
  return null;
}

export async function editCrmProposal(
  botId: string,
  instruction: string,
  ctx: { channel: string; threadTs: string }
): Promise<{ ok: boolean; error?: string }> {
  const fail = async (msg: string) => {
    await postToChannel(ctx.channel, {
      text: `⚠️ Couldn't update that CRM suggestion — ${msg}. Try rephrasing, or click *Apply* to use the current suggestion.`,
      threadTs: ctx.threadTs,
    }).catch(() => {});
    return { ok: false, error: msg };
  };

  const proposal = await getStoredCrmProposal(botId);
  if (!proposal) return fail("the suggestion expired");

  const runnerEmail = process.env.POST_MEETING_AGENT_EMAIL || "adam@reddy.io";
  const q = [
    `You are EDITING a CRM update suggestion per the user's instruction. Do NOT write to HubSpot — only revise the suggestion.`,
    `Deal: ${proposal.dealName} (${proposal.companyName}). Current deal stage: ${proposal.currentStageLabel ?? "unknown"}.`,
    `Valid stage labels (pick exactly one for suggestedStageLabel, or null for no change): ${JSON.stringify(proposal.stages)}`,
    `Current suggestion: ${JSON.stringify({ suggestedStageLabel: proposal.suggestedStageLabel, stageReason: proposal.stageReason, fieldSuggestions: proposal.fieldSuggestions })}`,
    `User instruction: ${JSON.stringify(instruction)}`,
    `Apply it. Use ONLY standard HubSpot deal/company properties. Return ONLY a fenced json block:`,
    "```json",
    `{ "suggestedStageLabel": string|null, "stageReason": string|null, "fieldSuggestions": [ { "object":"deal"|"company", "property": string, "currentValue": string|null, "suggestedValue": string, "reason": string } ] }`,
    "```",
    `Your FINAL message must be ONLY the json block.`,
  ].join("\n");

  const answer = await runOneshot(q, runnerEmail, `crmedit:${botId}`);
  if (!answer) return fail("the assistant didn't respond");
  const edited = parseCrmEdit(answer);
  if (!edited) return fail("couldn't parse the revised suggestion");

  const suggestedStageId = await resolveStageIdByLabel(edited.suggestedStageLabel ?? null);

  const updated: CrmProposal = {
    ...proposal,
    suggestedStageId,
    suggestedStageLabel: edited.suggestedStageLabel ?? null,
    stageReason: edited.stageReason ?? null,
    fieldSuggestions: Array.isArray(edited.fieldSuggestions) ? edited.fieldSuggestions : [],
  };
  await kv.set(crmProposalKey(botId), updated, { ex: CRM_TTL }).catch(() => {});
  await kv.set(`postmeeting:crm:ts:${ctx.threadTs}`, updated, { ex: CRM_TTL }).catch(() => {});

  const recUrl = recordingUrl(botId);
  const dealUrl = await hubspotDealUrl(proposal.dealId).catch(() => null);
  const msg = buildCrmMessage(updated, recUrl, dealUrl, true);
  await postToChannel(ctx.channel, { text: msg.text, blocks: msg.blocks, threadTs: ctx.threadTs }).catch(() => {});
  return { ok: true };
}

function buildCrmMessage(
  p: CrmProposal,
  recUrl: string,
  dealUrl: string | null,
  logged: boolean
): { text: string; blocks: object[] } {
  const text = `CRM updates suggested for ${p.companyName} — ${p.dealName}`;
  const slug = p.companyName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const boardUrl = boardLink({ customerSlug: slug || null });
  const dealLink = dealUrl ? ` · 🔗 <${dealUrl}|Open deal in HubSpot>` : "";
  const blocks: object[] = [
    { type: "header", text: { type: "plain_text", text: "🗂️  CRM updates", emoji: true } },
    {
      type: "context",
      elements: [{ type: "mrkdwn", text: `*${p.companyName}* · deal *${p.dealName}*${dealLink}` }],
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          `${logged ? "✅" : "⚠️"} *Logged to the deal* (auto): meeting summary + recording link${logged ? "" : " — _logging failed, see logs_"}\n` +
          `▶ <${recUrl}|Watch recording & read transcript>` +
          (dealUrl ? `\n🔗 <${dealUrl}|Open deal in HubSpot>` : "") +
          `\n📋 <${boardUrl}|Open on the board>`,
      },
    },
  ];

  const suggestionLines: string[] = [];
  if (p.suggestedStageLabel) {
    suggestionLines.push(
      `• *Stage:* ${p.currentStageLabel ?? "current"} → *${p.suggestedStageLabel}*${p.stageReason ? ` — ${p.stageReason}` : ""}`
    );
  }
  for (const f of p.fieldSuggestions) {
    suggestionLines.push(`• *${f.object} · ${f.property}:* ${f.currentValue ?? "—"} → *${f.suggestedValue}*${f.reason ? ` — ${f.reason}` : ""}`);
  }

  if (suggestionLines.length > 0) {
    blocks.push({ type: "divider" });
    blocks.push({
      type: "section",
      text: { type: "mrkdwn", text: `*Suggested — needs your OK:*\n${suggestionLines.join("\n")}` },
    });
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          action_id: CRM_APPLY_ACTION_ID,
          style: "primary" as const,
          text: { type: "plain_text", text: "✅ Apply CRM updates", emoji: true },
          value: p.botId,
        },
      ],
    });
    blocks.push({
      type: "context",
      elements: [{
        type: "mrkdwn",
        text: "Click *Apply* to write these to HubSpot — or reply to change/add fields, stages or properties before applying.",
      }],
    });
  } else {
    blocks.push({
      type: "context",
      elements: [{ type: "mrkdwn", text: "No stage/field changes suggested — the meeting was logged for the record." }],
    });
  }

  return { text, blocks };
}
