// ============================================================================
// POST-MEETING CRM SYNC (HubSpot as system of record).
//
// After a meeting, for an ALLOWLISTED company (Luminare only this phase):
//  - AUTO (no approval): log the meeting summary + a direct "Watch recording"
//    link onto the deal/company. Notes/meeting linkage is additive and safe.
//  - SUGGEST (approval): a Slack message proposing the deal STAGE move + any
//    standard field changes, with an "Apply CRM updates" button. Replies can
//    edit it; the button applies through the gated server path (the agent never
//    writes to HubSpot directly).
//
// The suggestion is generated by the shared agent (oneshot, read-only HubSpot),
// which returns stage/field changes in human terms; the SERVER resolves the
// stage label → internal id and performs the gated writes.
// ============================================================================

import { kv } from "@/lib/kv-client";
import { postToChannel } from "@/lib/slack";
import { selfBaseUrl } from "@/lib/work-items";
import { isCompanyWritable } from "@/lib/hubspot-guard";
import {
  logMeetingToHubSpot,
  updateDealStage,
  updateDealProperties,
  getDealPipelines,
  getCompanyContacts,
} from "@/lib/hubspot";

export const CRM_APPLY_ACTION_ID = "pm_crm_apply";
const CRM_TTL = 7 * 24 * 3600;

function recordingUrl(botId: string): string {
  const base = process.env.PUBLIC_BASE_URL ?? "https://gtm-jet.vercel.app";
  return `${base}/board/meeting/${botId}`;
}

export type CrmFieldSuggestion = {
  object: "deal" | "company";
  property: string;
  currentValue: string | null;
  suggestedValue: string;
  reason: string;
};

export type CrmProposal = {
  botId: string;
  companyId: string;
  companyName: string;
  dealId: string;
  dealName: string;
  currentStageLabel: string | null;
  suggestedStageId: string | null;
  suggestedStageLabel: string | null;
  stageReason: string | null;
  fieldSuggestions: CrmFieldSuggestion[];
};

export function crmProposalKey(botId: string): string {
  return `postmeeting:crm:bot:${botId}`;
}

export async function getStoredCrmProposal(botId: string): Promise<CrmProposal | null> {
  if (!botId) return null;
  return (await kv.get<CrmProposal>(crmProposalKey(botId)).catch(() => null)) ?? null;
}

// ----------------------------------------------------------------------------
// Suggestion generation (agent oneshot, read-only HubSpot)
// ----------------------------------------------------------------------------

function buildCrmPrompt(botId: string): string {
  return [
    `You are preparing a CRM-update SUGGESTION after a meeting. HubSpot is the system of record. READ-ONLY: do NOT write to HubSpot — only search/read.`,
    `MEETING BOT ID: ${botId}`,
    `STEP 1 — read the transcript + meta from the cloned KB ('_unsorted' is a real slug, so glob): corpora/success/customers/*/meetings/${botId}/transcript.txt and meta.json.`,
    `STEP 2 — identify the COMPANY the meeting is about and look it up in HubSpot (search companies). Get its id + name. Find the primary OPEN deal: its id, name, current dealstage LABEL, pipeline, and the pipeline's stage labels IN ORDER.`,
    `STEP 3 — write a concise meeting summary as HTML for hs_meeting_body: one short <p> recap + a "<p><strong>Next steps</strong></p>" followed by a <ul> of next steps with owners. Keep it tight.`,
    `STEP 4 — recommend whether the deal STAGE should change given what happened, and to which stage (MUST be one of the pipeline's stage labels, verbatim). One-line reason. If no change is warranted, suggestedStageLabel=null.`,
    `STEP 5 — suggest any STANDARD HubSpot deal/company field updates the conversation supports (e.g. closedate, amount, dealname). Only standard properties. Empty array if none.`,
    `Return ONLY a single fenced \`\`\`json block, nothing after it:`,
    "```json",
    `{`,
    `  "companyId": string, "companyName": string, "dealId": string, "dealName": string,`,
    `  "pipeline": string, "currentStageLabel": string, "stages": [string],`,
    `  "meetingSummaryHtml": string,`,
    `  "suggestedStageLabel": string|null, "stageReason": string|null,`,
    `  "fieldSuggestions": [ { "object": "deal"|"company", "property": string, "currentValue": string|null, "suggestedValue": string, "reason": string } ]`,
    `}`,
    "```",
    `CRITICAL: your FINAL message must be ONLY the single fenced json block.`,
  ].join("\n");
}

type RawCrm = {
  companyId?: string; companyName?: string; dealId?: string; dealName?: string;
  pipeline?: string; currentStageLabel?: string; stages?: string[];
  meetingSummaryHtml?: string;
  suggestedStageLabel?: string | null; stageReason?: string | null;
  fieldSuggestions?: CrmFieldSuggestion[];
};

function parseCrm(answer: string): RawCrm | null {
  const blocks: string[] = [];
  const fenced = answer.match(/```(?:json)?\s*([\s\S]*?)```/gi);
  if (fenced) for (const b of fenced) blocks.push(b.replace(/```(?:json)?\s*/i, "").replace(/```$/, "").trim());
  blocks.push(answer);
  for (const b of blocks) {
    const start = b.indexOf("{");
    const end = b.lastIndexOf("}");
    if (start < 0 || end <= start) continue;
    try {
      const o = JSON.parse(b.slice(start, end + 1)) as RawCrm;
      if (o && o.companyId && o.dealId) return o;
    } catch { /* try next */ }
  }
  return null;
}

async function runOneshot(question: string, userEmail: string, reqId: string): Promise<string | null> {
  const secret = process.env.MCP_INTERNAL_SECRET;
  if (!secret) return null;
  try {
    const res = await fetch(`${selfBaseUrl()}/api/agent/oneshot`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-reddy-internal": secret },
      body: JSON.stringify({ question, userEmail, oneshotRequestId: reqId, pollTimeoutMs: 600_000 }),
    });
    const json = (await res.json().catch(() => null)) as { ok?: boolean; answer?: string } | null;
    if (json?.ok && json.answer) return json.answer;
  } catch { /* swallow */ }
  return null;
}

export type CrmProposeResult = {
  ok: boolean;
  skipped?: string;
  companyName?: string;
  loggedMeetingId?: string | null;
  suggestedStageLabel?: string | null;
  fieldCount?: number;
  slackTs?: string;
  error?: string;
};

// Orchestrator: generate → auto-log meeting+recording → post Slack suggestion.
export async function proposeCrmFromMeeting(botId: string): Promise<CrmProposeResult> {
  try {
    if (!botId) return { ok: false, error: "missing botId" };
    const runnerEmail = process.env.POST_MEETING_AGENT_EMAIL || "adam@reddy.io";
    const answer = await runOneshot(buildCrmPrompt(botId), runnerEmail, `crm:${botId}`);
    if (!answer) return { ok: false, error: "crm agent unavailable or empty" };
    const raw = parseCrm(answer);
    if (!raw || !raw.companyId || !raw.dealId) return { ok: false, error: "could not parse crm JSON" };

    // GATE: only allowlisted companies get any write (auto-log included).
    if (!isCompanyWritable(raw.companyId)) {
      return { ok: true, skipped: `company ${raw.companyId} not writable (allowlist)`, companyName: raw.companyName };
    }

    // Resolve the suggested stage label → internal id within the deal's pipeline.
    let suggestedStageId: string | null = null;
    if (raw.suggestedStageLabel && raw.pipeline) {
      const pipelines = await getDealPipelines().catch(() => null);
      const stages = pipelines?.get(raw.pipeline) ?? [];
      suggestedStageId = stages.find((s) => s.label === raw.suggestedStageLabel)?.id ?? null;
    }

    // AUTO-LOG (no approval): meeting summary + direct recording link.
    const recUrl = recordingUrl(botId);
    const bodyHtml =
      (raw.meetingSummaryHtml ?? `<p>Meeting on ${raw.companyName ?? "the account"}.</p>`) +
      `<p>▶ <a href="${recUrl}">Watch the recording &amp; read the transcript</a></p>`;
    const contacts = await getCompanyContacts(raw.companyId).catch(() => []);
    const contactIds = contacts.slice(0, 10).map((c) => c.id);
    let loggedMeetingId: string | null = null;
    try {
      loggedMeetingId = await logMeetingToHubSpot({
        companyId: raw.companyId,
        dealId: raw.dealId,
        contactIds,
        title: raw.dealName ? `${raw.companyName ?? "Meeting"} — meeting` : "Meeting",
        bodyHtml,
        startISO: new Date().toISOString(),
      });
    } catch { /* surfaced below as no meeting id */ }

    // Stash the SUGGESTION (stage + fields) for the Apply button / chat-edit.
    const proposal: CrmProposal = {
      botId,
      companyId: raw.companyId,
      companyName: raw.companyName ?? "the account",
      dealId: raw.dealId,
      dealName: raw.dealName ?? "the deal",
      currentStageLabel: raw.currentStageLabel ?? null,
      suggestedStageId,
      suggestedStageLabel: raw.suggestedStageLabel ?? null,
      stageReason: raw.stageReason ?? null,
      fieldSuggestions: Array.isArray(raw.fieldSuggestions) ? raw.fieldSuggestions : [],
    };
    await kv.set(crmProposalKey(botId), proposal, { ex: CRM_TTL }).catch(() => {});

    // Post the Slack suggestion.
    let slackTs: string | undefined;
    const channel = process.env.SALES_TESTING_CHANNEL_ID;
    if (channel) {
      const res = await postToChannel(channel, buildCrmMessage(proposal, recUrl, !!loggedMeetingId)).catch(() => ({ ts: undefined }));
      slackTs = res.ts;
      if (slackTs) await kv.set(`postmeeting:crm:ts:${slackTs}`, proposal, { ex: CRM_TTL }).catch(() => {});
    }

    return {
      ok: true,
      companyName: proposal.companyName,
      loggedMeetingId,
      suggestedStageLabel: proposal.suggestedStageLabel,
      fieldCount: proposal.fieldSuggestions.length,
      ...(slackTs ? { slackTs } : {}),
    };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

// ----------------------------------------------------------------------------
// Apply (gated) — invoked by the Slack "Apply CRM updates" button.
// ----------------------------------------------------------------------------

export type CrmApplyResult = { ok: boolean; stageMoved: boolean; fieldsUpdated: number; errors: string[] };

export async function executeCrmProposal(proposal: CrmProposal): Promise<CrmApplyResult> {
  const res: CrmApplyResult = { ok: true, stageMoved: false, fieldsUpdated: 0, errors: [] };

  if (proposal.suggestedStageId) {
    try {
      res.stageMoved = await updateDealStage(proposal.companyId, proposal.dealId, proposal.suggestedStageId);
    } catch (err) {
      res.errors.push(`stage: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // Standard DEAL field updates only (company-field writes deferred with #3).
  const dealProps: Record<string, string> = {};
  for (const f of proposal.fieldSuggestions) {
    if (f.object === "deal" && f.property && f.suggestedValue) dealProps[f.property] = f.suggestedValue;
  }
  if (Object.keys(dealProps).length > 0) {
    try {
      const ok = await updateDealProperties(proposal.companyId, proposal.dealId, dealProps);
      if (ok) res.fieldsUpdated = Object.keys(dealProps).length;
      else res.errors.push("field update failed");
    } catch (err) {
      res.errors.push(`fields: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  res.ok = res.errors.length === 0;
  return res;
}

// ----------------------------------------------------------------------------
// Slack message
// ----------------------------------------------------------------------------

function buildCrmMessage(p: CrmProposal, recUrl: string, logged: boolean): { text: string; blocks: object[] } {
  const text = `CRM updates suggested for ${p.companyName} — ${p.dealName}`;
  const blocks: object[] = [
    { type: "header", text: { type: "plain_text", text: "🗂️  CRM updates", emoji: true } },
    {
      type: "context",
      elements: [{ type: "mrkdwn", text: `*${p.companyName}* · deal *${p.dealName}* · HubSpot is the system of record` }],
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          `${logged ? "✅" : "⚠️"} *Logged to the deal* (auto): meeting summary + recording link${logged ? "" : " — _logging failed, see logs_"}\n` +
          `▶ <${recUrl}|Watch recording & read transcript>`,
      },
    },
  ];

  const suggestionLines: string[] = [];
  if (p.suggestedStageLabel) {
    suggestionLines.push(
      `• *Stage:* ${p.currentStageLabel ?? "current"} → *${p.suggestedStageLabel}*${p.stageReason ? ` — ${p.stageReason}` : ""}`
    );
  }
  for (const f of p.fieldSuggestions) {
    suggestionLines.push(`• *${f.object} · ${f.property}:* ${f.currentValue ?? "—"} → *${f.suggestedValue}*${f.reason ? ` — ${f.reason}` : ""}`);
  }

  if (suggestionLines.length > 0) {
    blocks.push({ type: "divider" });
    blocks.push({
      type: "section",
      text: { type: "mrkdwn", text: `*Suggested — needs your OK:*\n${suggestionLines.join("\n")}` },
    });
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          action_id: CRM_APPLY_ACTION_ID,
          style: "primary" as const,
          text: { type: "plain_text", text: "✅ Apply CRM updates", emoji: true },
          value: p.botId,
        },
      ],
    });
    blocks.push({
      type: "context",
      elements: [{
        type: "mrkdwn",
        text: "Click *Apply* to write these to HubSpot — or reply to change/add fields, stages or properties before applying.",
      }],
    });
  } else {
    blocks.push({
      type: "context",
      elements: [{ type: "mrkdwn", text: "No stage/field changes suggested — the meeting was logged for the record." }],
    });
  }

  return { text, blocks };
}
